$(document).ready(function(){

 jQuery('#mobile-menu-active').meanmenu();


  $('.slider-active').owlCarousel({
    loop:true,
	navText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],
    nav:false,
	autoplay:true,
	smartSpeed:3000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
});
$('.testimonial-active').owlCarousel({
    loop:true,
	navText:false,
	nav:true,
	autoplay:false,
    autoplayTimeout:1000,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:2
        }
    }
});
$('.Blog-active').owlCarousel({
    autoplay:true,
	smartSpeed:3000,
	loop:true,
	navText:false,
	nav:true,
    responsive:{
        0:{
            items:1
        },
        767:{
            items:1
        },
        1000:{
            items:2
        }
    }
});
$('.image-link').magnificPopup({
  type: 'image',
  gallery:{
    enabled:true
  }
});

$('.brand_active').owlCarousel({
	autoplay:true,
	smartSpeed:30000,
	navText:false,
	nav:false,
	dots:false,
    responsive:{
        0:{
            items:1
        },
        767:{
            items:3
        },
        1000:{
            items:5
        }
    }
});

});